image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

resources:
  cpuLimit: "2"
  memLimit: 2700Mi
  cpuRequest: "1"
  memRequest: 2500Mi
  xmx: 2000m

service:
  http:
    internalPort: 8080