apiVersion: v1
kind: ConfigMap
data:
  application.properties: |+
    blobstore.gcs.bahamut.bucket.name=${BUCKET_NAME}
    blobstore.gcs.kakka.bucket.name={{ .Values.gcs.kakka.bucketName }}
    blobstore.gcs.kakka.tiamat.geocoder.file=tiamat/geocoder/tiamat_export_geocoder_latest.zip
    blobstore.gcs.haya.bucket.name={{ .Values.gcs.haya.bucketName }}
    blobstore.gcs.haya.latest.filename_without_extension=bahamut_latest
    blobstore.gcs.haya.import.folder=import
    spring.profiles.active=gcs-blobstore
    spring.application.name=bahamut
    spring.main.web-application-type=NONE
    bahamut.retry.maxAttempts=3
    bahamut.retry.maxDelay=5000
    bahamut.retry.backoff.multiplier=3
metadata:
  name: {{ template "bahamut.name" . }}-config
  namespace: {{ template "bahamut.name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}